packages:
  - '**'
ignoredBuiltDependencies:
  - '@parcel/watcher'
  - cypress
onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - '@swc/core'
  - esbuild
  - prisma
  - sharp
  - unrs-resolver
